language: rust
cache:
  cargo: true
rust:
- stable
- nightly
env:
- RUST_BACKTRACE=full
matrix:
  fast_finish: true
script: |
  #!/bin/bash
  cargo build --verbose
  cargo test --verbose
  cargo build --verbose --features 'gpu_cache'
  if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    # test nightly-only bench code
    cargo test --all-features
    # compile ./benches
    cargo bench --no-run
  else
    cargo test --features 'gpu_cache'
  fi
