[package]
name = "rusttype-dev"
version = "0.1.0"
description = "Tests, examples & benchmarks avoiding dependency feature bleed"
edition = "2018"
publish = false

[dependencies]
rusttype = { path = "../", features = ["gpu_cache"] }
glium = "0.25"
image = { version = "0.23", default-features = false, features = ["png"] }
arrayvec = { version = "0.5", default-features = false }
once_cell = "1"
blake2 = "0.8"
